# Generated by Django 4.0 on 2021-12-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_order', models.DateField()),
                ('status', models.CharField(choices=[('W przygotowaniu', 'W przygotowaniu'), ('Zamówiono', 'Zamówiono'), ('Wysłano', 'Wysłano'), ('Dostarczono', 'Dostarczono')], default='W przygotowaniu', max_length=15)),
                ('product_price', models.IntegerField()),
                ('transport_price', models.IntegerField()),
                ('customs_price', models.IntegerField()),
                ('total_weight', models.IntegerField()),
            ],
            options={
                'ordering': ('-date_of_order',),
            },
        ),
    ]
