# Generated by Django 4.0 on 2021-12-31 16:23

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_all_items_alter_order_customs_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customs_price_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fee_per_kg_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_price_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_transport_price_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transport_price_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_final_price_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_row_price_currency',
        ),
        migrations.AddField(
            model_name='order',
            name='PLN',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='USD',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='usd_price',
            field=djmoney.models.fields.MoneyField(currency_field_name='PLN', decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='PLN',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='USD',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='customs_price',
            field=djmoney.models.fields.MoneyField(currency_field_name='PLN', decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='fee_per_kg',
            field=djmoney.models.fields.MoneyField(currency_field_name='PLN', decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price',
            field=djmoney.models.fields.MoneyField(currency_field_name='USD', decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=djmoney.models.fields.MoneyField(currency_field_name='PLN', decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_transport_price',
            field=djmoney.models.fields.MoneyField(currency_field_name='PLN', decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='transport_price',
            field=djmoney.models.fields.MoneyField(currency_field_name='USD', decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_final_price',
            field=djmoney.models.fields.MoneyField(currency_field_name='PLN', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_row_price',
            field=djmoney.models.fields.MoneyField(currency_field_name='USD', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(),
        ),
    ]
