# Generated by Django 4.0 on 2022-01-02 19:50

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_pln_remove_order_usd_remove_product_pln_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customs_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='customs_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='fee_per_kg',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='fee_per_kg_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_transport_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_transport_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='usd_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='usd_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_final_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_final_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_row_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_row_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN'), ('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
    ]
