# Generated by Django 4.0 on 2022-01-03 20:45

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_usd_price_currency_alter_order_usd_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_final_price',
            field=djmoney.models.fields.MoneyField(currency_choices=[('PLN', 'PLN')], decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_final_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'PLN')], default='XYZ', editable=False, max_length=3),
        ),
    ]
