# Generated by Django 4.0 on 2022-01-03 20:48

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_product_purchase_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_final_price',
            field=djmoney.models.fields.MoneyField(currency_choices=[('PLN', 'PLN')], decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
    ]
